/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.locadora.gerenciadorveiculos.view;

import br.com.locadora.gerenciadorveiculos.uicomponents.ClientesTableModel;
import br.com.locadora.gerenciadorveiculos.controller.ClienteController;
import br.com.locadora.gerenciadorveiculos.dao.ClienteDAO;
import br.com.locadora.gerenciadorveiculos.factory.ConnectionFactory;
import br.com.locadora.gerenciadorveiculos.model.Cliente;
import java.sql.Connection;
import java.util.List;
import java.util.Optional;
import javax.swing.JOptionPane;

/**
 *
 * @author lucfg
 */
public class GerenciarClientes extends javax.swing.JFrame {
    
    private ClienteController clienteController = new ClienteController();
    private ClientesTableModel clientesTableModel = new ClientesTableModel(clienteController.listarClientes());
    private Cliente clienteTransfer;
    /**
     * Creates new form GerenciarClientes
     */
    public GerenciarClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dAlterarCliente = new javax.swing.JDialog();
        lNomeEdit = new javax.swing.JLabel();
        tFNomeEdit = new javax.swing.JTextField();
        lSobrenomeEdit = new javax.swing.JLabel();
        tFSobrenomeEdit = new javax.swing.JTextField();
        lCPFEdit = new javax.swing.JLabel();
        tFCPFEdit = new javax.swing.JFormattedTextField();
        lRGEdit = new javax.swing.JLabel();
        tFRGEdit = new javax.swing.JFormattedTextField();
        tFEnderecoEdit = new javax.swing.JTextField();
        lEnderecoEdit = new javax.swing.JLabel();
        bConfirmarAlteracao = new javax.swing.JButton();
        bVoltarEdit = new javax.swing.JButton();
        pCadastroCliente = new javax.swing.JPanel();
        lNome = new javax.swing.JLabel();
        tFNome = new javax.swing.JTextField();
        lSobrenome = new javax.swing.JLabel();
        tFSobrenome = new javax.swing.JTextField();
        lCPF = new javax.swing.JLabel();
        lRG = new javax.swing.JLabel();
        lEndereco = new javax.swing.JLabel();
        tFEndereco = new javax.swing.JTextField();
        tFCPF = new javax.swing.JFormattedTextField();
        tFRG = new javax.swing.JFormattedTextField();
        bIncluirCliente = new javax.swing.JButton();
        bListarClientes = new javax.swing.JButton();
        pTabelaClientes = new javax.swing.JPanel();
        sPTabelaClientes = new javax.swing.JScrollPane();
        tClientes = new javax.swing.JTable();
        bVoltar = new javax.swing.JButton();
        bAtualizarCliente = new javax.swing.JButton();
        bExcluirCliente = new javax.swing.JButton();

        dAlterarCliente.setTitle("Alterar Cliente");
        dAlterarCliente.setModal(true);
        dAlterarCliente.setSize(new java.awt.Dimension(617, 281));

        lNomeEdit.setText("Nome");

        tFNomeEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFNomeEditActionPerformed(evt);
            }
        });

        lSobrenomeEdit.setText("Sobrenome");

        lCPFEdit.setText("CPF");

        tFCPFEdit.setEditable(false);
        try {
            tFCPFEdit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lRGEdit.setText("RG");

        try {
            tFRGEdit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lEnderecoEdit.setText("Endereço");

        bConfirmarAlteracao.setText("Confirmar");
        bConfirmarAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConfirmarAlteracaoActionPerformed(evt);
            }
        });

        bVoltarEdit.setText("Voltar");
        bVoltarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dAlterarClienteLayout = new javax.swing.GroupLayout(dAlterarCliente.getContentPane());
        dAlterarCliente.getContentPane().setLayout(dAlterarClienteLayout);
        dAlterarClienteLayout.setHorizontalGroup(
            dAlterarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dAlterarClienteLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(dAlterarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dAlterarClienteLayout.createSequentialGroup()
                        .addGroup(dAlterarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lCPFEdit)
                            .addComponent(lEnderecoEdit)
                            .addComponent(tFCPFEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(dAlterarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lRGEdit)
                            .addComponent(tFRGEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(dAlterarClienteLayout.createSequentialGroup()
                        .addGroup(dAlterarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(dAlterarClienteLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bConfirmarAlteracao)
                                .addGap(18, 18, 18)
                                .addComponent(bVoltarEdit))
                            .addComponent(tFEnderecoEdit, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dAlterarClienteLayout.createSequentialGroup()
                                .addGroup(dAlterarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lNomeEdit)
                                    .addComponent(tFNomeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addGroup(dAlterarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lSobrenomeEdit)
                                    .addComponent(tFSobrenomeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(23, 23, 23))))
        );
        dAlterarClienteLayout.setVerticalGroup(
            dAlterarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dAlterarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dAlterarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSobrenomeEdit)
                    .addComponent(lNomeEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dAlterarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tFNomeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tFSobrenomeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dAlterarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lCPFEdit)
                    .addComponent(lRGEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dAlterarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tFCPFEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tFRGEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(lEnderecoEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tFEnderecoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(dAlterarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bConfirmarAlteracao)
                    .addComponent(bVoltarEdit))
                .addGap(20, 20, 20))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciar Clientes");

        lNome.setText("Nome");

        tFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFNomeActionPerformed(evt);
            }
        });

        lSobrenome.setText("Sobrenome");

        lCPF.setText("CPF");

        lRG.setText("RG");

        lEndereco.setText("Endereço");

        try {
            tFCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tFRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        bIncluirCliente.setText("Incluir Cliente");
        bIncluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIncluirClienteActionPerformed(evt);
            }
        });

        bListarClientes.setText("Listar Clientes");
        bListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListarClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pCadastroClienteLayout = new javax.swing.GroupLayout(pCadastroCliente);
        pCadastroCliente.setLayout(pCadastroClienteLayout);
        pCadastroClienteLayout.setHorizontalGroup(
            pCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastroClienteLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCadastroClienteLayout.createSequentialGroup()
                        .addComponent(bIncluirCliente)
                        .addGap(18, 18, 18)
                        .addComponent(bListarClientes)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCadastroClienteLayout.createSequentialGroup()
                        .addGroup(pCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tFEndereco)
                            .addGroup(pCadastroClienteLayout.createSequentialGroup()
                                .addGroup(pCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lNome)
                                    .addComponent(tFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addGroup(pCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lSobrenome)
                                    .addComponent(tFSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(19, 19, 19))
                    .addGroup(pCadastroClienteLayout.createSequentialGroup()
                        .addGroup(pCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lCPF)
                            .addComponent(lEndereco)
                            .addComponent(tFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(pCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lRG)
                            .addComponent(tFRG, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pCadastroClienteLayout.setVerticalGroup(
            pCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastroClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSobrenome)
                    .addComponent(lNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tFSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lCPF)
                    .addComponent(lRG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tFRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(lEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tFEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bIncluirCliente)
                    .addComponent(bListarClientes))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        sPTabelaClientes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tClientes.setModel(clientesTableModel);
        sPTabelaClientes.setViewportView(tClientes);

        javax.swing.GroupLayout pTabelaClientesLayout = new javax.swing.GroupLayout(pTabelaClientes);
        pTabelaClientes.setLayout(pTabelaClientesLayout);
        pTabelaClientesLayout.setHorizontalGroup(
            pTabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTabelaClientesLayout.createSequentialGroup()
                .addComponent(sPTabelaClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        pTabelaClientesLayout.setVerticalGroup(
            pTabelaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sPTabelaClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
        );

        bVoltar.setText("Voltar");

        bAtualizarCliente.setText("Atualizar Cliente");
        bAtualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtualizarClienteActionPerformed(evt);
            }
        });

        bExcluirCliente.setText("Excluir Cliente");
        bExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExcluirClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(pCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bExcluirCliente)
                                .addGap(18, 18, 18)
                                .addComponent(bAtualizarCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bVoltar))
                            .addComponent(pTabelaClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pTabelaClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bVoltar)
                    .addComponent(bAtualizarCliente)
                    .addComponent(bExcluirCliente))
                .addGap(14, 14, 14))
        );

        setSize(new java.awt.Dimension(1016, 736));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFNomeActionPerformed

    private void bIncluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIncluirClienteActionPerformed
        adicionarCliente(tFNome.getText(), tFSobrenome.getText(), tFRG.getText()
        , tFCPF.getText(), tFEndereco.getText());
        bListarClientes.doClick();
        limparForm();
    }//GEN-LAST:event_bIncluirClienteActionPerformed

    private void bListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListarClientesActionPerformed
        ClientesTableModel.listaClientes.clear();
        ClientesTableModel.listaClientes = listarClientes();
        clientesTableModel.fireTableDataChanged();
    }//GEN-LAST:event_bListarClientesActionPerformed

    private void bExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExcluirClienteActionPerformed
        int linha = tClientes.getSelectedRow();
        removerCliente(linha);
        bListarClientes.doClick();
    }//GEN-LAST:event_bExcluirClienteActionPerformed

    private void bAtualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtualizarClienteActionPerformed
        int linha = tClientes.getSelectedRow();
        if (linha != -1) {
            clienteTransfer = preencherCliente(linha);
        }    
    }//GEN-LAST:event_bAtualizarClienteActionPerformed

    private void tFNomeEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFNomeEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFNomeEditActionPerformed

    private void bConfirmarAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConfirmarAlteracaoActionPerformed
        ClientesTableModel.listaClientes.remove(clienteTransfer);
        alterarCliente(tFNomeEdit.getText(), tFSobrenomeEdit.getText(), tFRGEdit.getText()
            , tFCPFEdit.getText(), tFEnderecoEdit.getText());
    }//GEN-LAST:event_bConfirmarAlteracaoActionPerformed

    private void bVoltarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarEditActionPerformed
        dAlterarCliente.setVisible(false);
        bListarClientes.doClick();
    }//GEN-LAST:event_bVoltarEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtualizarCliente;
    private javax.swing.JButton bConfirmarAlteracao;
    private javax.swing.JButton bExcluirCliente;
    private javax.swing.JButton bIncluirCliente;
    private javax.swing.JButton bListarClientes;
    private javax.swing.JButton bVoltar;
    private javax.swing.JButton bVoltarEdit;
    private javax.swing.JDialog dAlterarCliente;
    private javax.swing.JLabel lCPF;
    private javax.swing.JLabel lCPFEdit;
    private javax.swing.JLabel lEndereco;
    private javax.swing.JLabel lEnderecoEdit;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lNomeEdit;
    private javax.swing.JLabel lRG;
    private javax.swing.JLabel lRGEdit;
    private javax.swing.JLabel lSobrenome;
    private javax.swing.JLabel lSobrenomeEdit;
    private javax.swing.JPanel pCadastroCliente;
    private javax.swing.JPanel pTabelaClientes;
    private javax.swing.JScrollPane sPTabelaClientes;
    private javax.swing.JTable tClientes;
    private javax.swing.JFormattedTextField tFCPF;
    private javax.swing.JFormattedTextField tFCPFEdit;
    private javax.swing.JTextField tFEndereco;
    private javax.swing.JTextField tFEnderecoEdit;
    private javax.swing.JTextField tFNome;
    private javax.swing.JTextField tFNomeEdit;
    private javax.swing.JFormattedTextField tFRG;
    private javax.swing.JFormattedTextField tFRGEdit;
    private javax.swing.JTextField tFSobrenome;
    private javax.swing.JTextField tFSobrenomeEdit;
    // End of variables declaration//GEN-END:variables

    private void adicionarCliente(String nome, String sobrenome, String RG,
        String CPF, String endereco) {
        Cliente cliente = new Cliente(nome, sobrenome, RG,
                CPF, endereco);

        if (clienteController.adicionarCliente(cliente)) {
            JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso!",
                    "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null,
                    "Falha ao cadastrar o cliente!\nVerifique se preencheu todos os campos ou se há campos duplicados.",
                    "Atenção!", JOptionPane.WARNING_MESSAGE);
        }    
    }

    private void limparForm() {
        tFNome.setText("");
        tFSobrenome.setText("");
        tFRG.setText("");
        tFCPF.setText("");
        tFEndereco.setText("");
    }

    private List<Cliente> listarClientes() {
        return clienteController.listarClientes();
    }

    private void removerCliente(int indice) {
        Cliente cliente = null;
        if (indice > -1)
            cliente = ClientesTableModel.listaClientes.get(indice);
        if (clienteController.removerCliente(cliente)) {
            JOptionPane.showMessageDialog(null, "Cliente excluído com sucesso!",
                    "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null,
                    "Falha ao excluir o cliente!\nO cliente possui veículos locados em seu nome\n"
                            + "ou nenhum cliente foi selecionado.",
                    "Atenção!", JOptionPane.WARNING_MESSAGE);
        } 
    }
    
    private void alterarCliente(String nome, String sobrenome, String RG,
        String CPF, String endereco) {
                
        Cliente cliente = new Cliente(nome, sobrenome, RG,
            CPF, endereco); 
        if (clienteController.alterarCliente(cliente)) {
            JOptionPane.showMessageDialog(null, "Cliente alterado com sucesso!",
                    "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null,
                    "Falha ao alterar o cliente!\nOs campos possuem valores inválidos\n"
                            + "ou nenhum cliente foi selecionado.",
                    "Atenção!", JOptionPane.WARNING_MESSAGE);
        } 
    }

    private Cliente preencherCliente(int indice) {
        Cliente cliente = ClientesTableModel.listaClientes.get(indice);
        tFNomeEdit.setText(cliente.getNome());
        tFSobrenomeEdit.setText(cliente.getSobrenome());
        tFCPFEdit.setText(cliente.getCPF());
        tFRGEdit.setText(cliente.getRG());
        tFEnderecoEdit.setText(cliente.getEndereco());
        dAlterarCliente.setLocationRelativeTo(this);
        dAlterarCliente.setVisible(true);
        return cliente;
    }
   
}
