/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.locadora.gerenciadorveiculos.view;

import br.com.locadora.gerenciadorveiculos.controller.VeiculoController;
import br.com.locadora.gerenciadorveiculos.model.Marca;
import br.com.locadora.gerenciadorveiculos.model.Veiculo;
import br.com.locadora.gerenciadorveiculos.uicomponents.VenderVeiculosTableModel;
import java.util.List;

/**
 *
 * @author lucfg
 */
public class VenderVeiculos extends javax.swing.JDialog {
    
    private VeiculoController veiculoController = new VeiculoController();
    private VenderVeiculosTableModel venderVeiculosTableModel = new VenderVeiculosTableModel(listarVeiculosDisponiveis());
    /**
     * Creates new form VenderVeiculos
     */
    public VenderVeiculos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGFiltroCategoria = new javax.swing.ButtonGroup();
        bGFiltroTipo = new javax.swing.ButtonGroup();
        pFiltroTipoVeiculo = new javax.swing.JPanel();
        rBMoto = new javax.swing.JRadioButton();
        rBAutomovel = new javax.swing.JRadioButton();
        rBVan = new javax.swing.JRadioButton();
        lFiltroTipo = new javax.swing.JLabel();
        pVeiculosDisponiveis = new javax.swing.JPanel();
        sPVeiculosDisponiveis = new javax.swing.JScrollPane();
        tVeiculosDisponiveis = new javax.swing.JTable();
        bFiltrar = new javax.swing.JButton();
        bVoltar = new javax.swing.JButton();
        bVender = new javax.swing.JButton();
        pFiltroCategoria = new javax.swing.JPanel();
        rBIntermediario = new javax.swing.JRadioButton();
        rBPopular = new javax.swing.JRadioButton();
        rBLuxo = new javax.swing.JRadioButton();
        lFiltroCategoria = new javax.swing.JLabel();
        cBMarca = new javax.swing.JComboBox(Marca.values());
        lMarca = new javax.swing.JLabel();

        bGFiltroCategoria.add(rBPopular);
        bGFiltroCategoria.add(rBIntermediario);
        bGFiltroCategoria.add(rBLuxo);

        bGFiltroTipo.add(rBAutomovel);
        bGFiltroTipo.add(rBMoto);
        bGFiltroTipo.add(rBVan);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vender Veiculos");
        setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        setModal(true);

        pFiltroTipoVeiculo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        rBMoto.setText("Motocicleta");

        rBAutomovel.setText("Automóvel");
        rBAutomovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBAutomovelActionPerformed(evt);
            }
        });

        rBVan.setText("Van");

        lFiltroTipo.setText("Tipo do Veículo");

        javax.swing.GroupLayout pFiltroTipoVeiculoLayout = new javax.swing.GroupLayout(pFiltroTipoVeiculo);
        pFiltroTipoVeiculo.setLayout(pFiltroTipoVeiculoLayout);
        pFiltroTipoVeiculoLayout.setHorizontalGroup(
            pFiltroTipoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFiltroTipoVeiculoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pFiltroTipoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rBAutomovel)
                    .addComponent(lFiltroTipo)
                    .addComponent(rBMoto)
                    .addComponent(rBVan))
                .addGap(164, 164, 164))
        );
        pFiltroTipoVeiculoLayout.setVerticalGroup(
            pFiltroTipoVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFiltroTipoVeiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lFiltroTipo)
                .addGap(18, 18, 18)
                .addComponent(rBAutomovel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBMoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBVan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sPVeiculosDisponiveis.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        //VenderVeiculosTableModel venderVeiculosTableModel = new VenderVeiculosTableModel(listarVeiculosDisponiveis());
        tVeiculosDisponiveis.setModel(venderVeiculosTableModel);
        sPVeiculosDisponiveis.setViewportView(tVeiculosDisponiveis);

        javax.swing.GroupLayout pVeiculosDisponiveisLayout = new javax.swing.GroupLayout(pVeiculosDisponiveis);
        pVeiculosDisponiveis.setLayout(pVeiculosDisponiveisLayout);
        pVeiculosDisponiveisLayout.setHorizontalGroup(
            pVeiculosDisponiveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sPVeiculosDisponiveis, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
        );
        pVeiculosDisponiveisLayout.setVerticalGroup(
            pVeiculosDisponiveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pVeiculosDisponiveisLayout.createSequentialGroup()
                .addComponent(sPVeiculosDisponiveis, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap())
        );

        bFiltrar.setText("Aplicar Filtro");
        bFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFiltrarActionPerformed(evt);
            }
        });

        bVoltar.setText("Voltar");
        bVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarActionPerformed(evt);
            }
        });

        bVender.setText("Vender Veículo");
        bVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVenderActionPerformed(evt);
            }
        });

        pFiltroCategoria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        rBIntermediario.setText("Intermediário");
        rBIntermediario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBIntermediarioActionPerformed(evt);
            }
        });

        rBPopular.setText("Popular");
        rBPopular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBPopularActionPerformed(evt);
            }
        });

        rBLuxo.setText("Luxo");
        rBLuxo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBLuxoActionPerformed(evt);
            }
        });

        lFiltroCategoria.setText("Categoria");

        javax.swing.GroupLayout pFiltroCategoriaLayout = new javax.swing.GroupLayout(pFiltroCategoria);
        pFiltroCategoria.setLayout(pFiltroCategoriaLayout);
        pFiltroCategoriaLayout.setHorizontalGroup(
            pFiltroCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFiltroCategoriaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pFiltroCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rBPopular)
                    .addComponent(lFiltroCategoria)
                    .addComponent(rBIntermediario)
                    .addComponent(rBLuxo))
                .addGap(164, 164, 164))
        );
        pFiltroCategoriaLayout.setVerticalGroup(
            pFiltroCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFiltroCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lFiltroCategoria)
                .addGap(18, 18, 18)
                .addComponent(rBPopular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBIntermediario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBLuxo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lMarca.setText("Marca");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lMarca)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bVender)
                                .addGap(18, 18, 18)
                                .addComponent(bVoltar))
                            .addComponent(pVeiculosDisponiveis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cBMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(bFiltrar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(pFiltroCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(pFiltroTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pFiltroCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pFiltroTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(lMarca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bFiltrar)
                    .addComponent(cBMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(pVeiculosDisponiveis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bVoltar)
                    .addComponent(bVender))
                .addGap(28, 28, 28))
        );

        setSize(new java.awt.Dimension(807, 535));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rBAutomovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBAutomovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBAutomovelActionPerformed

    private void bFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFiltrarActionPerformed
        VenderVeiculosTableModel.listaVeiculos.clear();
        VenderVeiculosTableModel.listaVeiculos = listarVeiculosDisponiveis();
        venderVeiculosTableModel.fireTableDataChanged();
    }//GEN-LAST:event_bFiltrarActionPerformed

    private void bVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bVoltarActionPerformed

    private void bVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bVenderActionPerformed

    private void rBPopularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBPopularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBPopularActionPerformed

    private void rBIntermediarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBIntermediarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBIntermediarioActionPerformed

    private void rBLuxoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBLuxoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBLuxoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VenderVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VenderVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VenderVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VenderVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    
        //Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VenderVeiculos().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bFiltrar;
    private javax.swing.ButtonGroup bGFiltroCategoria;
    private javax.swing.ButtonGroup bGFiltroTipo;
    private javax.swing.JButton bVender;
    private javax.swing.JButton bVoltar;
    private javax.swing.JComboBox<String> cBMarca;
    private javax.swing.JLabel lFiltroCategoria;
    private javax.swing.JLabel lFiltroTipo;
    private javax.swing.JLabel lMarca;
    private javax.swing.JPanel pFiltroCategoria;
    private javax.swing.JPanel pFiltroTipoVeiculo;
    private javax.swing.JPanel pVeiculosDisponiveis;
    private javax.swing.JRadioButton rBAutomovel;
    private javax.swing.JRadioButton rBIntermediario;
    private javax.swing.JRadioButton rBLuxo;
    private javax.swing.JRadioButton rBMoto;
    private javax.swing.JRadioButton rBPopular;
    private javax.swing.JRadioButton rBVan;
    private javax.swing.JScrollPane sPVeiculosDisponiveis;
    private javax.swing.JTable tVeiculosDisponiveis;
    // End of variables declaration//GEN-END:variables

    private List<Veiculo> listarVeiculosDisponiveis() {
        return veiculoController.listarVeiculosDisponiveis();
    }

}
